backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: public/uploads
public_folder: /uploads

local_backend: true

collections:
  # Settings
  - name: 'settings'
    label: 'Settings'
    files:
      - file: 'content/settings/global.md'
        label: 'Global'
        name: 'global'
        fields:
          # Site Title
          - { label: 'Site Title', name: 'siteTitle', widget: 'string' }

          # Default Metadata
          - {
              label: 'Default Metadata',
              name: 'defaultMetadata',
              widget: 'object',
              fields:
                [
                  { label: 'Title', name: 'title', widget: 'string' },
                  { label: 'Description', name: 'description', widget: 'text' },
                  { label: 'Share Image', name: 'shareImage', widget: 'image', required: false },
                  { label: 'Twitter Username', name: 'twitterUsername', widget: 'string', required: false },
                  { label: 'Twitter Card Type', name: 'twitterCardType', widget: 'select', options: ['summary', 'summary_large_image', 'app', 'player'], required: false },
                ],
            }

      - file: 'content/settings/navigation.md'
        label: 'Navigation'
        name: 'navigation'
        fields:
          # Header Navigation
          - {
              label: 'Header Navigation',
              label_singular: 'Navigation Item',
              name: headerNavigation,
              widget: 'list',
              fields:
                [
                  { label: 'Name', name: 'name', widget: string },
                  { label: Path, name: path, widget: relation, collection: 'pages', search_fields: ['metadata.slug'], value_field: 'metadata.slug', display_fields: ['name'] },
                ],
            }

  # Pages
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'content/pages/home.md'
        label: 'Home'
        name: 'home'
        fields:
          # Name
          - { label: 'Name', name: 'name', widget: 'string' }

          # Content
          - {
              label: 'Content',
              name: 'content',
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Content, name: content, widget: markdown },
                  {
                    label: Image,
                    name: image,
                    widget: object,
                    fields: [{ label: Source, name: source, widget: image }, { label: Alt, name: alt, widget: string }, { label: Caption, name: caption, widget: string }],
                  },
                ],
            }

          # Business Details
          - {
              label: 'Business Details',
              name: 'businessDetails',
              widget: 'object',
              fields:
                [
                  { label: 'Phone Number', name: 'phoneNumber', widget: 'object', fields: [{ label: 'Text', name: 'text', widget: string }, { label: 'Href', name: 'href', widget: string }] },
                  { label: 'Hours', name: 'hours', widget: 'text' },
                  { label: 'Address', name: 'address', widget: 'text' },
                  { label: 'Map', name: 'map', widget: 'object', fields: [{ label: 'Map Title', name: title, widget: string }, { label: 'Map Source', name: source, widget: string }] },
                ],
            }

          # Pricelist
          - {
              label: Pricelist,
              name: pricelist,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Button,
                    name: button,
                    widget: object,
                    fields:
                      [
                        { label: Text, name: text, widget: string },
                        { label: Href, name: href, widget: relation, collection: 'pages', search_fields: ['metadata.slug'], value_field: 'metadata.slug', display_fields: ['name'] },
                      ],
                  },
                ],
            }

          # Testimonials
          - {
              label: Testimonials,
              name: testimonials,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: 'Reviews',
                    label_singular: 'Review',
                    name: 'reviews',
                    widget: 'list',
                    summary: '{{fields.alt}} - {{fields.image}}',
                    fields:
                      [
                        { label: Stars, name: stars, widget: number, min: 1, max: 5 },
                        { label: When, name: when, widget: string },
                        { label: Content, name: content, widget: text },
                        { label: Author, name: author, widget: string },
                      ],
                  },
                ],
            }

          # Gallery
          - {
              label: Gallery,
              name: gallery,
              widget: object,
              fields:
                [
                  {
                    label: 'Images',
                    label_singular: 'Image',
                    name: 'images',
                    widget: 'list',
                    summary: '{{fields.alt}} - {{fields.image}}',
                    fields:
                      [
                        { label: Source, name: source, widget: image },
                        { label: Alt, name: alt, widget: string },
                        { label: Columns, name: columns, widget: number, default: 1, min: 1 },
                        { label: Rows, name: rows, widget: number, default: 1, min: 1 },
                      ],
                  },
                ],
            }

          # Metadata
          - {
              label: 'Metadata',
              name: 'metadata',
              widget: 'object',
              fields:
                [
                  { label: 'Title', name: 'title', widget: 'string' },
                  { label: 'Slug', name: slug, widget: string },
                  { label: 'Description', name: 'description', widget: 'text', required: false },
                  { label: 'Share Image', name: 'shareImage', widget: 'image', required: false },
                  { label: 'Twitter Username', name: 'twitterUsername', widget: 'string', required: false },
                  { label: 'Twitter Card Type', name: 'twitterCardType', widget: 'select', options: ['summary', 'summary_large_image', 'app', 'player'], required: false },
                  { label: 'Overwrite Title', name: 'titleOverwrite', widget: boolean, required: false },
                ],
            }

      - file: 'content/pages/about.md'
        label: 'About'
        name: 'about'
        fields:
          # Name
          - { label: 'Name', name: 'name', widget: 'string' }

          # Content
          - {
              label: 'Content',
              name: 'content',
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Content, name: content, widget: markdown },
                  {
                    label: Image,
                    name: image,
                    widget: object,
                    fields: [{ label: Source, name: source, widget: image }, { label: Alt, name: alt, widget: string }, { label: Caption, name: caption, widget: string }],
                  },
                ],
            }

          # Metadata
          - {
              label: 'Metadata',
              name: 'metadata',
              widget: 'object',
              fields:
                [
                  { label: 'Title', name: 'title', widget: 'string' },
                  { label: 'Slug', name: slug, widget: string },
                  { label: 'Description', name: 'description', widget: 'text', required: false },
                  { label: 'Share Image', name: 'shareImage', widget: 'image', required: false },
                  { label: 'Twitter Username', name: 'twitterUsername', widget: 'string', required: false },
                  { label: 'Twitter Card Type', name: 'twitterCardType', widget: 'select', options: ['summary', 'summary_large_image', 'app', 'player'], required: false },
                  { label: 'Overwrite Title', name: 'titleOverwrite', widget: boolean, required: false },
                ],
            }

      - file: 'content/pages/pricelist.md'
        label: 'Pricelist'
        name: 'pricelist'
        fields:
          # Name
          - { label: 'Name', name: 'name', widget: 'string' }

          # Pricelist
          - {
              label: Pricelist,
              name: pricelist,
              widget: object,
              fields:
                [
                  {
                    label: PDFS,
                    label_singular: PDF,
                    name: pdfs,
                    widget: list,
                    fields: [{ label: Name, name: name, widget: string }, { label: Description, name: description, widget: string }, { label: File, name: file, widget: file }],
                  },
                ],
            }

          # Metadata
          - {
              label: 'Metadata',
              name: 'metadata',
              widget: 'object',
              fields:
                [
                  { label: 'Title', name: 'title', widget: 'string' },
                  { label: 'Slug', name: slug, widget: string },
                  { label: 'Description', name: 'description', widget: 'text', required: false },
                  { label: 'Share Image', name: 'shareImage', widget: 'image', required: false },
                  { label: 'Twitter Username', name: 'twitterUsername', widget: 'string', required: false },
                  { label: 'Twitter Card Type', name: 'twitterCardType', widget: 'select', options: ['summary', 'summary_large_image', 'app', 'player'], required: false },
                  { label: 'Overwrite Title', name: 'titleOverwrite', widget: boolean, required: false },
                ],
            }

      - file: 'content/pages/seasonals.md'
        label: 'Seasonals'
        name: 'seasonals'
        fields:
          # Name
          - { label: 'Name', name: 'name', widget: 'string' }

          # Content
          - { label: 'Content', name: 'content', widget: object, fields: [{ label: Heading, name: heading, widget: string }, { label: Content, name: content, widget: markdown }] }

          # Seasonals
          - {
              label: 'Seasonals',
              name: 'seasonals',
              widget: list,
              summary: '{{fields.name}}',
              fields:
                [
                  { label: Name, name: name, widget: string },
                  { label: Description, name: description, widget: text, required: false },
                  {
                    label: 'Images',
                    name: images,
                    widget: list,
                    summary: '{{fields.alt}} - {{fields.image}}',
                    fields: [{ label: Source, name: source, widget: image }, { label: Alt, name: alt, widget: string }],
                  },
                ],
            }

          # Metadata
          - {
              label: 'Metadata',
              name: 'metadata',
              widget: 'object',
              fields:
                [
                  { label: 'Title', name: 'title', widget: 'string' },
                  { label: 'Slug', name: slug, widget: string },
                  { label: 'Description', name: 'description', widget: 'text', required: false },
                  { label: 'Share Image', name: 'shareImage', widget: 'image', required: false },
                  { label: 'Twitter Username', name: 'twitterUsername', widget: 'string', required: false },
                  { label: 'Twitter Card Type', name: 'twitterCardType', widget: 'select', options: ['summary', 'summary_large_image', 'app', 'player'], required: false },
                  { label: 'Overwrite Title', name: 'titleOverwrite', widget: boolean, required: false },
                ],
            }

      - file: 'content/pages/events.md'
        label: 'Events'
        name: 'events'
        fields:
          # Name
          - { label: 'Name', name: 'name', widget: 'string' }

          # Headline
          - {
              label: 'Headline',
              name: headline,
              widget: object,
              fields: [{ label: Source, name: source, widget: image }, { label: Alt, name: alt, widget: string }, { label: Caption, name: caption, widget: string, required: false }],
            }

          # Content
          - {
              label: 'Content',
              name: 'content',
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Content, name: content, widget: markdown },
                  {
                    label: Image,
                    name: image,
                    widget: object,
                    fields: [{ label: Source, name: source, widget: image }, { label: Alt, name: alt, widget: string }, { label: Caption, name: caption, widget: string, required: false }],
                  },
                ],
            }

          # Metadata
          - {
              label: 'Metadata',
              name: 'metadata',
              widget: 'object',
              fields:
                [
                  { label: 'Title', name: 'title', widget: 'string' },
                  { label: 'Slug', name: slug, widget: string },
                  { label: 'Description', name: 'description', widget: 'text', required: false },
                  { label: 'Share Image', name: 'shareImage', widget: 'image', required: false },
                  { label: 'Twitter Username', name: 'twitterUsername', widget: 'string', required: false },
                  { label: 'Twitter Card Type', name: 'twitterCardType', widget: 'select', options: ['summary', 'summary_large_image', 'app', 'player'], required: false },
                  { label: 'Overwrite Title', name: 'titleOverwrite', widget: boolean, required: false },
                ],
            }
