backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: public/uploads
public_folder: /uploads

local_backend: true

collections:
  # Settings
  - name: 'settings'
    label: 'Settings'
    files:
      - file: 'content/settings/global.md'
        label: 'Global'
        name: 'global'
        fields:
          # Site Title
          - { label: 'Site Title', name: 'siteTitle', widget: 'string' }

          # Default Metadata
          - {
              label: 'Default Metadata',
              name: 'defaultMetadata',
              widget: 'object',
              fields:
                [
                  { label: 'Title', name: 'title', widget: 'string' },
                  { label: 'Description', name: 'description', widget: 'text' },
                  { label: 'Share Image', name: 'shareImage', widget: 'image', required: false },
                  { label: 'Twitter Username', name: 'twitterUsername', widget: 'string', required: false },
                  { label: 'Twitter Card Type', name: 'twitterCardType', widget: 'select', options: ['summary', 'summary_large_image', 'app', 'player'], required: false },
                ],
            }

          # Site Banner
          - {
              label: 'Site Banner',
              name: 'siteBanner',
              widget: object,
              fields:
                [
                  { label: 'Short Text', name: 'shortText', widget: string, required: false },
                  { label: 'Long Text', name: 'longText', widget: string, required: false },
                  {
                    label: 'Link',
                    name: 'link',
                    widget: object,
                    required: false,
                    fields:
                      [
                        { label: Href, name: href, widget: string, required: false },
                        { label: Text, name: text, widget: string, required: false },
                        { label: External, name: external, widget: boolean, default: false, required: false },
                      ],
                  },
                ],
            }

      - file: 'content/settings/navigation.md'
        label: 'Navigation'
        name: 'navigation'
        fields:
          # Header Navigation
          - {
              label: 'Header Navigation',
              label_singular: 'Navigation Item',
              name: headerNavigation,
              widget: 'list',
              fields:
                [
                  { label: 'Name', name: 'name', widget: string },
                  { label: Path, name: path, widget: relation, collection: 'pages', search_fields: ['metadata.slug'], value_field: 'metadata.slug', display_fields: ['name'] },
                  {
                    label: 'Children',
                    label_singular: 'Item',
                    name: 'children',
                    widget: 'list',
                    fields:
                      [
                        { label: 'Name', name: 'name', widget: string },
                        { label: Path, name: path, widget: relation, collection: 'pages', search_fields: ['metadata.slug'], value_field: 'metadata.slug', display_fields: ['name'] },
                      ],
                  },
                ],
            }

      - file: 'content/settings/paths.md'
        label: 'Paths'
        name: paths
        fields:
          - {
              label: Paths,
              label_singular: Path,
              name: paths,
              widget: list,
              fields:
                [
                  { label: Parent, name: parent, widget: relation, collection: pages, search_fields: ['metadata.slug'], value_field: '{{metadata.slug}}', display_fields: ['name'] },
                  {
                    label: Children,
                    label_singular: Child,
                    name: children,
                    required: false,
                    widget: list,
                    fields: [{ label: Child, name: child, widget: relation, collection: pages, search_fields: ['metadata.slug'], value_field: '{{metadata.slug}}', display_fields: ['name'] }],
                  },
                ],
            }

      - file: 'content/settings/pricelist.md'
        label: Pricelist
        name: pricelist
        fields:
          - {
              label: PDFS,
              label_singular: PDF,
              name: pdfs,
              widget: list,
              fields:
                [
                  { label: Name, name: name, widget: string },
                  { label: Description, name: description, widget: string },
                  { label: File, name: file, widget: file, media_folder: '/public/uploads/pricelist' },
                ],
            }
  # # Pages
  # - name: 'pages'
  #   label: 'Pages'
  #   label_singular: 'Page'
  #   summary: '{{name}}'
  #   identifier_field: metadata.slug
  #   create: true
  #   folder: content/pages
  #   fields:
  #     # Name
  #     - { label: 'Name', name: 'name', widget: 'string' }

  #     # Parent
  #     - {
  #         label: Parent,
  #         name: parent,
  #         widget: relation,
  #         collection: pages,
  #         search_fields: ['metadata.slug'],
  #         value_field: '{{metadata.title}}__{{metadata.slug}}',
  #         display_fields: ['name'],
  #         required: false,
  #       }

  #     # Sections
  #     - {
  #         label: 'Sections',
  #         label_singular: Section,
  #         name: 'sections',
  #         widget: 'list',
  #         types:
  #           [
  #             {
  #               label: Hero,
  #               name: hero,
  #               widget: object,
  #               collapsed: true,
  #               fields:
  #                 [
  #                   { label: Heading, name: heading, widget: string },
  #                   { label: Subheading, name: subheading, widget: string },
  #                   { label: Image, name: image, widget: object, fields: [{ label: Name, name: name, widget: string }, { label: Ext, name: ext, widget: string, default: 'jpg' }] },
  #                   {
  #                     label: CTA,
  #                     name: cta,
  #                     widget: object,
  #                     collapsed: true,
  #                     fields:
  #                       [
  #                         { label: Heading, name: heading, widget: string, required: false },
  #                         { label: Text, name: text, widget: string, required: false },
  #                         {
  #                           label: Button,
  #                           name: button,
  #                           widget: object,
  #                           fields: [{ label: Text, name: text, widget: string, required: false }, { label: Href, name: href, widget: string, required: false }],
  #                           required: false,
  #                         },
  #                       ],
  #                     required: false,
  #                   },
  #                 ],
  #             },
  #             { label: 'Content', name: 'content', widget: 'object', fields: [{ label: Heading, name: heading, widget: string }, { label: 'Content', name: content, widget: 'markdown' }] },
  #             {
  #               label: Image,
  #               name: image,
  #               widget: object,
  #               fields: [{ label: Source, name: source, widget: image }, { label: Alt, name: alt, widget: string }, { label: Caption, name: caption, widget: string }],
  #             },
  #             { label: Newsletter, name: newsletter, widget: object, fields: [{ label: Placeholder, name: placeholder, widget: string }] },
  #           ],
  #       }

  #     # Metadata
  #     - {
  #         label: 'Metadata',
  #         name: 'metadata',
  #         widget: 'object',
  #         fields:
  #           [
  #             { label: 'Title', name: 'title', widget: 'string' },
  #             { label: 'Slug', name: slug, widget: string },
  #             { label: 'Description', name: 'description', widget: 'text', required: false },
  #             { label: 'Share Image', name: 'shareImage', widget: 'image', required: false },
  #             { label: 'Twitter Username', name: 'twitterUsername', widget: 'string', required: false },
  #             { label: 'Twitter Card Type', name: 'twitterCardType', widget: 'select', options: ['summary', 'summary_large_image', 'app', 'player'], required: false },
  #             { label: 'Overwrite Title', name: 'titleOverwrite', widget: boolean, required: false },
  #           ],
  #       }
